feat(basic hooks) allow groups by method then type
- Introduces the terminology of "Basic Hooks" and "Advanced Hooks"
   - Any reference of "Legacy Hooks" to "Basic Hooks".
   - Renames any reference of "Async Hooks" to "Advanced Hooks"
- Introduces support for registering basic hook objects  grouped by method.  To prevent a lot of code changes, it converts the new format to the old format, internally.

There are now two supported Basic Hook registration formats.  The new format prevents having to scoll past all other methods' hooks in order to see the after hooks.

```ts
const  newFormat = {
  find: {
    before: [hook1, hook2, hook3],
    after: [hook4, hook5, hook6],
    error: [error1, error2, error3]
  },
  get: {
    before: [hook1, hook2, hook3],
    after: [hook4, hook5, hook6],
    error: [error1, error2, error3]
  },
}
```