[dove/cli] Address strictNullCheck error on app.test.ts
Strict null checks are on in our tsconfig.json... so we run into the following error without this PR.
https://stackoverflow.com/a/58401023/370238

```
test/app.test.ts:36:28 - error TS2532: Object is possibly 'undefined'.

36         assert.strictEqual(response.data.name, 'NotFound')
                              ~~~~~~~~
```